## DBの指定
database.host = 127.0.0.1
database.port = 3306

## urlで直接指定する場合は上の設定は無視される
database.url = jdbc:mysql://127.0.0.1:3306/BMS_v24?autoReconnect=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

## ユーザ名とパスワード
database.user = root
database.password = andre123
